version: 0.1.{build}

skip_tags: true

environment:
    matrix:
        - nodejs_version: "4"
        - nodejs_version: "5"
        - nodejs_version: "6"
        - nodejs_version: "stable"

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

test_script:
    - node --version
    - npm --version
    - npm run test

build: off
