language: node_js
node_js:
    - 4
    - 5
    - 6
    - stable

sudo: false

services:
    - mongodb

after_script:
    - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
